<<<<<<< HEAD
# Site
#repository: sproogen/resume-theme
#favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Srikanth Murleedharan
title: Technical Lead/Deputy Manager

# Dark Mode (true/false/never)
darkmode: false

# Social links
linkedin_username: srikanthmurleedharan

# Additional icon links
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Srikanth and I'm a technical lead/software developer. I have worked at a number of companies gaining teamwork, technical and leadership skills.

  I am most skilled in: <mark>Python/R/VBA</mark> and <mark>Eating Sambhar Rice</mark>

content:
  
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: RNTBCI
       # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Technical Lead/Deputy Manager
        caption: August 2021 - Present
        quote: >
            Solving business problems using advanced technologies.
        description: | # this will include new lines to allow paragraphs
            Developed various PoC projects focussing on emerging technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Cass Business School (now, renamed as Bayes Business School), London
        caption: 2009 - 2010
        sub_title: MSc Investment Management
        quote: >
          CFA Programme Partner, CISI Centre of Excellence, Ranked 19 in Financial Times Rankings of European Business Schools in 2014 and a Global Ranking of 45 in 2015. The course is a Chartered Financial Analyst Institute (CFA) Programme Partner and is accredited by the Chartered Institute of Securities & Investment (CISI) and the Chartered Alternative Investment Analysts Association (CAIA). 
        description: | # this will include new lines to allow paragraphs
          During my time at Cass, I learnt about the valuation of financial instruments. 

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in software programming some of my other interests and hobbies are:
      - Reading books
      - Listening to music

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
=======
theme: jekyll-theme-minimal
>>>>>>> efccecca1a8d02e62527e5cbcdf6bbf4f3a48a5b
